In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.size

6

In [5]:
a.itemsize
## bytes
## 1 byte = 8 bit, 8 bytes = 32 bits

4

In [6]:
a.dtype

dtype('int32')

In [7]:
##total size
size = a.size * a.itemsize
size

24

## changing specific elements, rows, columns etc..

In [8]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a[1,:]

array([4, 5, 6])

In [10]:
## iterating specific value
## c
a[1,0]

4

In [11]:
a[1,0] = 12

In [12]:
a

array([[ 1,  2,  3],
       [12,  5,  6]])

In [13]:
b = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [14]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [15]:
b[0,1:6:2]

array([2, 4, 6])

## 3d exmple

In [16]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [17]:
c
## first 2 rows are for 0 index, and next one for 1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
c.ndim

3

In [19]:
c[0]
c[1]

array([[5, 6],
       [7, 8]])

In [20]:
c[1,0]

array([5, 6])

In [21]:
c[1,0,0]

5

In [22]:
c[1,0,0] = 8

In [23]:
c[1,0,0]

8

In [24]:
c

array([[[1, 2],
        [3, 4]],

       [[8, 6],
        [7, 8]]])

In [25]:
c[:,1] = [[55,56],[57,58]]



In [26]:
c

array([[[ 1,  2],
        [55, 56]],

       [[ 8,  6],
        [57, 58]]])

## just to keep in mind

In [27]:
a1 = np.array([1,2,3])
a1.ndim

1

In [28]:
a2 = np.array([[1,2,3]])
a2.ndim

2

In [29]:
a3 = np.array([[[1,2,3]]])
a3.ndim

3

## more 

In [30]:
np.zeros(shape = (2,2), dtype = "int")

## or

np.zeros((2,2), int)

array([[0, 0],
       [0, 0]])

In [31]:
np.ones(shape = (3,3), dtype = "int")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [32]:
np.full(shape = (3,3), fill_value = 15, dtype = "int")
np.full((3,3),15)

array([[15, 15, 15],
       [15, 15, 15],
       [15, 15, 15]])

In [33]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [34]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
np.full_like(a = b, fill_value = 15)

## a is a default variable

array([[15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15]])

In [36]:
np.random.rand(2,2)

## here paranthesis values represents the shape of the matrix

array([[0.50643238, 0.32149644],
       [0.24745362, 0.5778365 ]])

In [37]:
np.random.randint(low = 1, high = 11, size = [2,2] )

## have to provide start and end point, end point is exclusive

array([[3, 3],
       [2, 3]])

In [38]:
## generates square matrix

np.identity(5, dtype = "int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## copying the array


In [39]:
## carefull whie copiying

In [40]:
a

array([[ 1,  2,  3],
       [12,  5,  6]])

In [41]:
d = a.copy()

In [42]:
d

array([[ 1,  2,  3],
       [12,  5,  6]])

In [43]:
d[0,1] = 4

In [44]:
d

array([[ 1,  4,  3],
       [12,  5,  6]])

In [45]:
a

array([[ 1,  2,  3],
       [12,  5,  6]])

## linear algebra

In [68]:
## to do matrix math, cloumn of 1st matrix = rows of 2nd matrix

In [69]:
e = np.ones((3,2), dtype = int)
e.shape

(3, 2)

In [70]:
f = np.array([[1,2],[3,4]])
f.shape

(2, 2)

In [71]:
np.matmul(e,f)
## 3*2 will be the shape

array([[4, 6],
       [4, 6],
       [4, 6]])

## find the determinant

In [50]:
a1 = np.array([[1,2],[3,4]])

In [51]:
np.linalg.det(a1)

-2.0000000000000004

In [52]:
a2 = np.array([10,20])
a3 = np.array([30,40])

In [53]:
np.sum([a2,a3])

## total sum

100

In [54]:
np.sum([a2,a3], axis = 0)
np.sum([a2,a3], axis = 1)

array([30, 70])

## reorganizing arrays

In [55]:
before = np.array([[1,2,3,4],[5,6,7,8]])

In [56]:
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
before.shape

## the product of 2*4 is 8, so this reshape can only happen if the multiplication of raw and column is 8

(2, 4)

In [67]:
after = before.reshape((4,2))
after = before.reshape((2,4))
after = before.reshape((8,1))
after = before.reshape((1,8))
after

array([[1, 2, 3, 4, 5, 6, 7, 8]])

## vertically stack

In [77]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [82]:
stack1 = np.vstack((v1,v2,v2,v2))
stack1

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [84]:
stack1.ndim

2

## horizintal stack

In [79]:
h1 = np.array([1,2,3])
h2 = np.array([4,5,6])

In [83]:
stack2 = np.hstack((h1,h2,h1,h2))
stack2

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [85]:
stack2.ndim

1

## miscellaneous

In [92]:
file = np.genfromtxt("file.txt", delimiter = ",", dtype = "int")
file

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

## masking and advanced index

In [93]:
mask = file > 50

In [94]:
file[mask]

array([ 60,  70,  80,  90, 100, 110, 120])

In [95]:
new = np.array([1,2,3,4,5,6])

In [99]:
new[[0,1,2]]

## giving the index value

array([1, 2, 3])

## any and all

In [114]:
np.any(file > 10 , axis = 1)

array([ True,  True,  True])

In [112]:
np.all(file > 50, axis = 0)

array([False, False, False, False])